version: '3'

services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   expose:
  #     - "3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     NODE_ENV: development
  #   env_file:
  #     - .env.dev

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: awawYpkyWR26LL2HWDMUux2HMLM4hikE
      MYSQL_DATABASE: sport_database
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
